### ISSUE TITLE
Compilation fails on Rust 1.0.0 Beta

### ISSUE THREAD

**Issue by toolness** [toolness/pbpaste-rs#1]
It looks like there are at least 3 things needed to fix this, because the beta channel doesn't allow the use of unstable features:
- [x] Remove the use of `libc::strcpy`, as `libc` is unstable. I _guess_ this means we'll have to either write our own strcpy or find something on crates.io--perhaps [`rlibc`](https://crates.io/crates/rlibc) will suffice.
- [x] Remove the use of `std::env::set_exit_status`, as it's unstable. This seems quite odd, since we want the command-line tool to exit with a nonzero exit code if unrecognized/invalid command-line arguments are provided.
- [x] Remove the use of slice patterns, as they're unstable. This is particularly odd since slice patterns are documented in [The Rust Programming Language book's chapter on Patterns](https://doc.rust-lang.org/book/patterns.html), and aren't listed in the completely separate [Unstable Rust](https://doc.rust-lang.org/book/unstable.html) section of that book, which implies that they're a stable language feature. I filed this as https://github.com/rust-lang/rust/issues/24076.

**Comment by SSheldon** [comment]
`libc` can be used if you use the version from crates.io: https://crates.io/crates/libc

Alternatively, in this case it looks like you don't really need `libc`'s `strcpy`, you could just use `std::ptr::copy` instead.
